[workspace]
members = [
  "src/setup",
  "src/led-roulette",
  "src/uart",
  "src/i2c",
  "src/led-compass",
  "src/punch-o-meter",
  "src/snake-game",
]

[profile.release]
codegen-units = 1
debug = true
lto = true
